name: CI
on:
  push: { branches: [master] }
  pull_request: { branches: [master] }
  schedule: [ cron: '3 15 9 * *' ]

jobs:
  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@f72ff1a1336129f29bf0166c0fd0ca6cf1bcb38c  # v1.2.1

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update
      - run: sudo apt-get install cppcheck groff python3-wheel
      - run: pip3 install --user cpplint
      - run: ./lint.sh
      - run: |
          ! groff -wall -mandoc -Thtml doc/xsuspender.1 |& grep ' warning: '

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update
      - run: sudo apt-get install libglib2.0-dev libwnck-3-dev procps make cmake pkg-config
      - env:
          CC: ${{ matrix.compiler }}
          DISPLAY: mock-for-later
        run: |
          cd build
          cmake -DCMAKE_C_FLAGS=-Werror -DCMAKE_INSTALL_PREFIX=~ ..
          make
          make install
          cpack
          xvfb-run make test
